linters:
  enable-all: true
  disable:
  #   - depguard
  #   - exhaustruct
  #   - gochecknoglobals
  #   - nlreturn
  #   - nolintlint
    - tenv # The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting.
  #   - testableexamples
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

# issues:
#   exclude-files:
#     - example_test.go
#   exclude-rules:
#     - path: _test\.go
#       linters:
#         - err113
#         - forcetypeassert
#         - funlen
# linters-settings:
#   cyclop:
#     skip-tests: true
#   lll:
#     line-length: 200
