// Package querybm provides a simple SQL query builder and mapper that works well with models generated by sqlc.
package querybm

import "github.com/tecowl/querybm/statement"

// Builder defines the interface for components that can build SQL statement parts.
type Builder interface {
	// Build modifies the given statement by adding SQL components to it.
	Build(st *statement.Statement)
}

// Condition is an alias for Builder used specifically for WHERE clause conditions.
type Condition = Builder
